version: "3"
services:
    web:
        build: ./PublicTransportApi/
        ports:
            - "8000:5000"
            - "8001:5001"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "8500:1433"
    front:
        build: ./PublicTrandportClient/public-transport-client/
	ports: 
            - '4200:4200'
